#!/bin/bash
#CSUB -J geta
#CSUB -q c01
#CSUB -o geta.out
#CSUB -e geta.error
#CSUB -n 176
#CSUB -R span[ptile=88]

geta.pl --genome {PROJ_LOTUS_ZC}/Gifu/00.assemble_result/Lotus_GifuT2T_v1.0.fasta \
--RM_species_Dfam Viridiplantae --RM_species_RepBase Viridiplantae \
--pe1 {PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_flower_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_flower_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_flower_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_leaf_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_leaf_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_leaf_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi10_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi10_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi10_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi21_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi21_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi21_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi45_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi45_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi45_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_pod_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_pod_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_pod_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi02_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi02_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi02_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi10_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi10_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi10_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi21_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi21_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi21_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi45_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi45_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi45_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_hpi48_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_hpi48_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_hpi48_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_uni_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_uni_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_uni_rep3-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_stem_rep1-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_stem_rep2-R1.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_stem_rep3-R1.fastq.gz \
--pe2 {PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_flower_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_flower_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_flower_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_leaf_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_leaf_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_leaf_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi10_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi10_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi10_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi21_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi21_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi21_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi45_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi45_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_nodule_dpi45_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_pod_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_pod_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_pod_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi02_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi02_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi02_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi10_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi10_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi10_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi21_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi21_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi21_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi45_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi45_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_dpi45_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_hpi48_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_hpi48_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_hpi48_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_uni_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_uni_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_root_uni_rep3-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_stem_rep1-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_stem_rep2-R2.fastq.gz,{PROJ_LOTUS_ZC}/data/Gifu/RNA/clean/Gifu_stem_rep3-R2.fastq.gz \
--protein {PROJ_LOTUS_ZC}/Gifu/09.annotation/06.braker/douke_pep.fasta \
--config {SOFTWARE_ZC}/geta-2.7.1/conf_for_big_genome.txt \
--augustus_species Gifu_T2T \
--HMM_db {SOFTWARE_ZC}/Pfam/Pfam-A,{SOFTWARE_ZC}/Pfam/Pfam-B \
--BUSCO_lineage_dataset {SOFTWARE_ZC}/busco_downloads/lineages/embryophyta_odb10 \
--out_prefix Gifu_T2T \
--gene_prefix Gifu_T2T \
--cpu 176 \
--max_used_read_num 2000000000
